export const  mockMatches = [
  {
    id: 1,
    team1: { name: "Mumbai Indians", shortName: "MI"},
    team2: { name: "Chennai Super Kings", shortName: "CSK"},
    status: "live",
    venue: "Wankhede Stadium, Mumbai",
    date: "2024-04-15",
    time: "19:30",
    score: {
      team1: { runs: 185, wickets: 6, overs: 20 },
      team2: { runs: 142, wickets: 8, overs: 18.3 },
    },
    result: null,
  },
  {
    id: 2,
    team1: { name: "Royal Challengers Bangalore", shortName: "RCB"},
    team2: { name: "Delhi Capitals", shortName: "DC" },
    status: "upcoming",
    venue: "M. Chinnaswamy Stadium, Bangalore",
    date: "2024-04-16",
    time: "15:30",
    score: null,
    result: null,
  },
  {
    id: 3,
    team1: { name: "Kolkata Knight Riders", shortName: "KKR"},
    team2: { name: "Rajasthan Royals", shortName: "RR"},
    status: "upcoming",
    venue: "Eden Gardens, Kolkata",
    date: "2024-04-16",
    time: "19:30",
    score: null,
    result: null,
  },
]


export const mockPointsTable = [
  {
    position: 1,
    team: { name: "Rajasthan Royals", shortName: "RR"},
    matches: 14,
    won: 11,
    lost: 3,
    points: 22,
    nrr: "+0.633",
    form: ["W", "W", "L", "W", "W"],
  },
  {
    position: 2,
    team: { name: "Gujarat Titans", shortName: "GT"},
    matches: 14,
    won: 10,
    lost: 4,
    points: 20,
    nrr: "+0.316",
    form: ["W", "L", "W", "W", "L"],
  },
  {
    position: 3,
    team: { name: "Lucknow Super Giants", shortName: "LSG"},
    matches: 14,
    won: 9,
    lost: 5,
    points: 18,
    nrr: "+0.284",
    form: ["L", "W", "W", "L", "W"],
  },
  {
    position: 4,
    team: { name: "Royal Challengers Bangalore", shortName: "RCB"},
    matches: 14,
    won: 8,
    lost: 6,
    points: 16,
    nrr: "-0.253",
    form: ["W", "L", "L", "W", "W"],
  },
  {
    position: 5,
    team: { name: "Delhi Capitals", shortName: "DC"},
    matches: 14,
    won: 7,
    lost: 7,
    points: 14,
    nrr: "+0.204",
    form: ["L", "W", "L", "L", "W"],
  },
  {
    position: 6,
    team: { name: "Punjab Kings", shortName: "PBKS"},
    matches: 14,
    won: 7,
    lost: 7,
    points: 14,
    nrr: "-0.162",
    form: ["W", "L", "W", "L", "L"],
  },
  {
    position: 7,
    team: { name: "Kolkata Knight Riders", shortName: "KKR"},
    matches: 14,
    won: 6,
    lost: 8,
    points: 12,
    nrr: "+0.146",
    form: ["L", "L", "W", "L", "W"],
  },
  {
    position: 8,
    team: { name: "Sunrisers Hyderabad", shortName: "SRH"},
    matches: 14,
    won: 6,
    lost: 8,
    points: 12,
    nrr: "-0.379",
    form: ["L", "W", "L", "L", "L"],
  },
  {
    position: 9,
    team: { name: "Chennai Super Kings", shortName: "CSK" },
    matches: 14,
    won: 4,
    lost: 10,
    points: 8,
    nrr: "-0.203",
    form: ["L", "L", "L", "W", "L"],
  },
  {
    position: 10,
    team: { name: "Mumbai Indians", shortName: "MI"},
    matches: 14,
    won: 3,
    lost: 11,
    points: 6,
    nrr: "-0.506",
    form: ["L", "L", "L", "L", "W"],
  },
]